LOG_LEVEL: "DEBUG"  # Levels: DEBUG - INFO - WARNING - ERROR - CRITICAL

APP_HOST: "0.0.0.0"
APP_PORT: 5309
APP_VERSION: "v1.2"
DEBUG: True

ENABLED_ENDPOINTS: # allow all by default
  - "resource"
  - "dataset"
  - "gtaa"
  - "pong"
  - "health"
  - "link"

DATA_CATALOG_GRAPH: "http://data.rdlabs.beeldengeluid.nl/datacatalog/"

BENG_DATA_DOMAIN: "http://data.beeldengeluid.nl/"
URI_NISV_ORGANISATION: "https://www.beeldengeluid.nl/"

SPARQL_ENDPOINT: "https://cat.apis.beeldengeluid.nl/sparql"
SPARQL_ENDPOINT_HEALTH_URL: "https://cat.apis.beeldengeluid.nl/sparql"

MUZIEKWEB_DATA_DOMAIN: "https://data.muziekweb.nl/"
MUZIEKWEB_SPARQL_ENDPOINT: "https://api.data.muziekweb.nl/datasets/MuziekwebOrganization/Muziekweb/services/Muziekweb/sparql"

SWAGGER_UI_PATH: "/swagger"

HEALTH_TIMEOUT_SEC: 5.0
