name: Check Project

on:
  push:

jobs:
  check-project:
    uses: beeldengeluid/gha-workflows/.github/workflows/check-poetry-project.yml@f96114651b1976bf74f358a35e58336da0cce5ab # v2026.01.29
    with:
      poetry-version: 2.1.4
    permissions:
      contents: read
