name: Check Project

on:
  push:

jobs:
  check-project:
    uses: beeldengeluid/gha-workflows/.github/workflows/check-poetry-project.yml@c2ef18304765f1682ffced8a3d5679ae7d40087a # v2025.12.04
    with:
      poetry-version: 2.1.4
    permissions:
      contents: read
