name: Check Project

on:
  push:

jobs:
  check-project:
    uses: beeldengeluid/gha-workflows/.github/workflows/check-poetry-project.yml@d89babc3901e525997141a8f5f146ebbac4ebb67 # v2025.12.10
    with:
      poetry-version: 2.1.4
    permissions:
      contents: read
